name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger info
        run: echo "The job was triggered by push event"

      - name: OS info
        run: echo "Running on Linux runner"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Repo cloned
        run: echo "Repo cloned successfully"

      - name: Ready
        run: echo "Ready to test"

      - name: List files
        run: ls

      - name: Status
        run: echo "Job completed successfully"